post http://localhost:3000/register/
Content-Type: application/json

{
  "username": "kar",
  "name": "Adam Richard",
  "password": "richard_5671",
  "gender": "male",
  "location": "Detroit"
}
###
put http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "kar",
  "oldPassword": "richard_5671",
  "newPassword": "richard@123"
}

